# Generated by Django 5.1.6 on 2025-02-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0004_alter_user_email_alter_user_phone_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
